In [1]:
!pip install -U sentence-transformers faiss-cpu


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 63.3 MB/s eta 0:00:00


In [2]:
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np


In [3]:
model = SentenceTransformer("all-MiniLM-L6-v2")


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [4]:
texts = [
    "Artificial intelligence focuses on building systems that can perform tasks typically requiring human intelligence, such as reasoning, learning, and decision-making.",

    "Machine learning is a subfield of artificial intelligence that enables systems to learn patterns from data without being explicitly programmed.",

    "Deep learning is a subset of machine learning that uses multi-layer neural networks and has achieved strong results in image recognition and natural language processing.",

    "AI techniques are widely used in medical diagnosis, healthcare analytics, and clinical decision support systems to improve patient outcomes.",

    "In healthcare applications, artificial intelligence can assist doctors by analyzing medical images, predicting diseases, and personalizing treatment plans.",

    "Natural language processing allows machines to understand and generate human language, enabling applications such as chatbots, document search, and text summarization.",

    "Computer vision focuses on enabling machines to interpret visual information from images and videos, and is widely applied in autonomous vehicles and medical imaging.",

    "Football is a popular sport played worldwide, with millions of fans and professional leagues across different countries.",

    "Professional football requires physical fitness, tactical understanding, and teamwork, and is one of the most watched sports globally.",

    "Data quality and preprocessing play a critical role in the performance of machine learning and artificial intelligence systems."
]

len(texts)


10

In [5]:
embeddings = model.encode(texts)
embeddings = np.array(embeddings).astype("float32")

embeddings.shape


(10, 384)

In [6]:
dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)

index.add(embeddings)
index.ntotal


10

In [7]:
# Define a query
query = "Applications of artificial intelligence in healthcare"

# Create embedding for the query
query_embedding = model.encode(query)
query_embedding = np.array([query_embedding]).astype("float32")

# Retrieve top-1 result
distances, indices = index.search(query_embedding, k=1)

distances, indices


(array([[0.4251418]], dtype=float32), array([[4]]))

In [8]:
print(texts[indices[0][0]])


In healthcare applications, artificial intelligence can assist doctors by analyzing medical images, predicting diseases, and personalizing treatment plans.


In [9]:
# Retrieve top-3 results
distances, indices = index.search(query_embedding, k=3)

distances, indices


(array([[0.4251418, 0.5960002, 0.9740906]], dtype=float32), array([[4, 3, 0]]))

In [10]:
for idx in indices[0]:
    print("-", texts[idx])


- In healthcare applications, artificial intelligence can assist doctors by analyzing medical images, predicting diseases, and personalizing treatment plans.
- AI techniques are widely used in medical diagnosis, healthcare analytics, and clinical decision support systems to improve patient outcomes.
- Artificial intelligence focuses on building systems that can perform tasks typically requiring human intelligence, such as reasoning, learning, and decision-making.


In [11]:
# Retrieve top-5 results
distances, indices = index.search(query_embedding, k=5)

distances, indices


(array([[0.4251418, 0.5960002, 0.9740906, 1.1451213, 1.1796505]],
       dtype=float32),
 array([[4, 3, 0, 1, 6]]))

In [12]:
for idx in indices[0]:
    print("-", texts[idx])


- In healthcare applications, artificial intelligence can assist doctors by analyzing medical images, predicting diseases, and personalizing treatment plans.
- AI techniques are widely used in medical diagnosis, healthcare analytics, and clinical decision support systems to improve patient outcomes.
- Artificial intelligence focuses on building systems that can perform tasks typically requiring human intelligence, such as reasoning, learning, and decision-making.
- Machine learning is a subfield of artificial intelligence that enables systems to learn patterns from data without being explicitly programmed.
- Computer vision focuses on enabling machines to interpret visual information from images and videos, and is widely applied in autonomous vehicles and medical imaging.
